### ISSUE TITLE
Test cases to view collision

### ISSUE THREAD

**Issue by atharvad17** [DependableSystemsLab/SwarmFuzz#1]
Hello, I am a fellow student and was curious to test and analyze the results based on collisions. I have tried many possible inputs to determine whether a collision took place between the drones or not. However, I haven't seen any case where a collision has taken place. I wanted to request you to share any more particular results along with the input values, so as to observe a collision and analyze the received outputs. Thanks!

**Comment by ElaineYao** [comment]
Hi @atharvad17,

Thanks for your interest in our paper! 

I've updated collision cases in `./collision_cases` identified by SwarmFuzz and provided instructions in the README's `Collision cases found by SwarmFuzz` section for reproducing collisions using parameters found by SwarmFuzz. 

Also, if you didn't observe any collision when running SwarmFuzz, consider (1) adding more mission seeds (because not every mission has SPVs) and (2) running SwarmFuzz for at least 24 hours. Since missions with denser swarms and under larger GPS spoofing are more vulnerable to SPVs, you could start with a 15-drone swarm and 10m GPS spoofing. For example, in README step 5, run `swarmfuzz(200, 300, 10, 15)` instead of `swarmfuzz(200, 201, 5, 5)`.

Let me know if there is any question!

**Comment by ElaineYao** [comment]
Let me know if you still cannot find any collision cases after trying the above. Thanks.
